Improve configuration file generation
marius-team/marius pull request #14
Opened 2021-04-05 06:19 UTC by AnzeXie

Added options for configuration generation and config arguments to preprocess.py. 
E.g.
--generate_config, --config_dir, --model.embedding_size

Added tests for above features.

2021-04-06 18:01 UTC, JasonMoho requested changes

2021-04-06 18:01 UTC, JasonMoho commented on tools/preprocess.py
> -        output_bash_cmds(args.output_directory, args.dataset)
output_bash_cmds is no longer used but still imported in this file.

2021-04-10 19:02 UTC, JasonMoho requested changes

2021-04-10 19:02 UTC, JasonMoho commented on tools/preprocess.py
> +    parser = argparse.ArgumentParser(
Usage is still unclear, we should improve this according to our conversation over slack

2021-04-10 21:40 UTC, AnzeXie commented on tools/preprocess.py
>      parser.add_argument('output_directory', metavar='output_directory', type=str, help='Directory to put graph data')
preprocessed data and configuration file generated are put into the same directory now (specified by args.output_directory)

2021-04-10 21:55 UTC, AnzeXie commented on tools/config_templates/default_configs.txt
> +general.device=CPU*CPU*GPU
The first value before "*" is the default value. Values after first * are the valid values for the option.

2021-04-10 21:58 UTC, AnzeXie commented on tools/preprocess.py
> +    parser.add_argument('--generate_config', '-gc', metavar='generate_config',
Added the multi-gpu config generation option

2021-04-10 22:04 UTC, JasonMoho submitted a review, later dismissed
Ship it! 🚢

2021-04-10 22:22 UTC, JasonMoho approved these changes

2021-04-10 22:25 UTC, merged